### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by xbelanch** [zonuexe/emacs-copyit#2]
Sure it's my bad, but everytime I execute the command ``copyit-pandoc-export-to-html``  I see this message: ``apply: Wrong type argument: stringp, 1``.

Any idea of what I'm doing wrong?

**Comment by zonuexe** [comment]
@xbelanch Thank you for pointing that out!
I remembered this package for several years, and thank you for giving me the chance to fix it.

The fix was released as Version [0.1.0](https://github.com/zonuexe/emacs-copyit/releases/tag/0.1.0).
